<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<OutputType>Exe</OutputType>
	<TargetFramework>net10.0-windows</TargetFramework>
	<UseWindowsForms>true</UseWindowsForms>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\XISO.Core\XISO.Core\XISO.Core.csproj" />
    <ProjectReference Include="..\..\XISO.OriginalXbox\XISO.OriginalXbox\XISO.OriginalXbox.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SharpCompress" Version="0.50.4" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\XISO.Core\XISO.Core\Data\ToolkitConfiguration.json">
      <Link>Data\ToolkitConfiguration.json</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\XISO.Core\XISO.Core\Data\GameTitles.json">
      <Link>Data\GameTitles.json</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>